#! /bin/sh

# System V init script for chrony
# Adapted from the script already in meta-networking for ntpd

### BEGIN INIT INFO
# Provides:        chrony
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start chrony time daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

DAEMON=/usr/sbin/chronyd
PIDFILE=/var/run/chrony/chronyd.pid
STATE_DIR=/home/root/.ne
STATE_CONFIG=$STATE_DIR/chrony.conf
DISABLED_FILE=$STATE_DIR/ntp_disabled
CONFIG_FILE=/etc/chrony.conf

if test -r "$STATE_CONFIG"; then
	CONFIG_FILE=$STATE_CONFIG
fi

test -x "$DAEMON" -a -r "$CONFIG_FILE" || exit 0

# Source function library.
. /etc/init.d/functions

# Functions to do individual actions
startdaemon(){
	echo -n "Starting chronyd: "
	if test -e "$DISABLED_FILE"; then
		echo "disabled"
		return 0
	fi
	start-stop-daemon --start --oknodo --pidfile $PIDFILE --startas $DAEMON -- -f "$CONFIG_FILE" "$@"
	echo "done"
}
stopdaemon(){
	echo -n "Stopping chronyd: "
	start-stop-daemon --stop --oknodo -p $PIDFILE
	echo "done"
}

case "$1" in
  start)
	startdaemon
	;;
  stop)
  	stopdaemon
	;;
  force-reload | restart | reload)
  	stopdaemon
	startdaemon
	;;
  status)
	status /usr/sbin/chronyd;
	exit $?
	;;
  *)
	echo "Usage: chronyd { start | stop | status | restart | reload }" >&2
	exit 1
	;;
esac

exit 0
